export default {
    postaConstants: {
        // Contracts revert codes
        REVERT_POST_TEXT_TOO_LONG: "POST_TEXT_TOO_LONG",
        HUMAN_NOT_REGISTERED: "HUMAN_NOT_REGISTERED",
        POSTA_INVALID_SIGNATURE: "POSTA_INVALID_SIGNATURE",
        POSTA_SIGNER_CANNOT_BE_POSTER: "POSTA_SIGNER_CANNOT_BE_POSTER"
    }
}